plugins {
	id 'java'
	id 'pmd'
	id 'jacoco'
	id 'org.springframework.boot' version '3.2.2' 
	id 'io.spring.dependency-management' version '1.1.4'
	id ("org.sonarqube") version "4.4.1.3373"
}

sonarqube {
    properties {
        property "sonar.gradle.skipCompile", "true"
        property "sonar.host.url", "https://sonarcloud.io"
        property "sonar.organization", "advprog-2026-b16-project"
        property "sonar.projectKey", "advprog-2026-B16-project_individual-preparation"
    }
}
pmd {
	ignoreFailures = false
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
description = 'Individual preparation for the Advanced Programming course at the Faculty of Computer Science Universitas Indonesia'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
