name: Continuous Integration (CI)

on:
  push:
    branches: [main, ci-cd-iqbal]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin'"
          java-version: "21"

      # Run Tests & Linter for main, ci-cd, and pull requests
      - name : Run Tests & Linter
        if: github.ref !='refs/heads/ci-cd-iqbal'
        run: ./gradlew test pmdMain

      # Run linter only for ci-cd-iqbal branch
      - name: Run Linter only (ci-cd-iqbal)
        if: github.ref == 'refs/heads/ci-cd-iqbal'
        run: ./gradlew pmdMain
