name: Continuous Integration (CI)

on:
  push:
    branches: [main, ci-cd, ci-cd-zafran]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Run Tests & Linter for main, ci-cd, and pull requests
      - name: Run Tests & Linter
        if: github.ref != 'refs/heads/ci-cd-zafran'
        run: ./gradlew test pmdMain

      # Run Linter only for ci-cd-zafran branch
      - name: Run Linter only (ci-cd-zafran)
        if: github.ref == 'refs/heads/ci-cd-zafran'
        run: ./gradlew pmdMain

      # SonarCloud Scan for main, ci-cd, and pull requests
      - name: SonarCloud Scan
        if: github.ref != 'refs/heads/ci-cd-zafran'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build sonar --info